language: go
go:
  - "1.10"

script:
  - GOOS=linux GOARCH=amd64 go build -o lxd-exporter

before_deploy:
  - tar -zcf lxd-exporter-linux-amd64.tar.gz lxd-exporter
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - lxd-exporter-linux-amd64.tar.gz
  on:
    repo: BaritoLog/lxd_exporter
    tags: true
